version: '3.8'

services:
  postgres-db:
    container_name: ts-node-express
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always